### ISSUE TITLE
Error while executing follow_wall.py

### ISSUE THREAD

**Issue by TilletJ** [QuentinCar/Hexabot#39]
I got an error while executing `rosrun phantomx_gazebo follow_wall.py`:

```
Traceback (most recent call last):
  File "/home/joris/IS_gazebo/AQADAC/workspaceRos/src/phantomx/phantomx_gazebo/scripts/follow_wall.py", line 13, in <module>
    z = robot.follow_wall()
  File "/home/joris/IS_gazebo/AQADAC/workspaceRos/src/phantomx/phantomx_gazebo/src/phantomx_gazebo/phantomx.py", line 120, in follow_wall
    delta_t = (self.now - self.time)
AttributeError: PhantomX instance has no attribute 'now'
```

**Comment by Aureleb** [comment]
https://github.com/QuentinCar/Hexabot/commit/a5ca7a7a8f8c218f20b27dbb823ae20be628acf1
